name: Go

on:
  push:
    branches: [ master ]
  pull_request: {}

jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:

    - name: Set up Go 1.13
      uses: actions/setup-go@v1
      with:
        go-version: 1.13
      id: go

    - name: Check out code into the Go module directory
      uses: actions/checkout@v2

    - name: Build All
      run: |
        GOOS=aix GOARCH=ppc64 go build -o cut.aix-ppc64 .
        #GOOS=android GOARCH=386 go build -o cut.android-386 .
        #GOOS=android GOARCH=amd64 go build -o cut.android-amd64 .
        #GOOS=android GOARCH=arm go build -o cut.android-arm . 
        #GOOS=android GOARCH=arm64 go build -o cut.android-arm64 .
        GOOS=darwin GOARCH=386 go build -o cut.darwin-386 .
        GOOS=darwin GOARCH=amd64 go build -o cut.darwin-amd64 .
        #GOOS=darwin GOARCH=arm go build -o cut.darwin-arm .
        #GOOS=darwin GOARCH=arm64 go build -o cut.darwin-arm64 .
        GOOS=dragonfly GOARCH=amd64 go build -o cut.dragonfly-amd64 .
        GOOS=freebsd GOARCH=386 go build -o cut.freebsd-386 .
        GOOS=freebsd GOARCH=amd64 go build -o cut.freebsd-amd64 .
        GOOS=freebsd GOARCH=arm go build -o cut.freebsd-arm .
        GOOS=illumos GOARCH=amd64 go build -o cut.illumos-amd64 .
        GOOS=js GOARCH=wasm go build -o cut.js-wasm .
        GOOS=linux GOARCH=386 go build -o cut.linux-386 .
        GOOS=linux GOARCH=amd64 go build -o cut.linux-amd64 .
        GOOS=linux GOARCH=arm go build -o cut.linux-arm .
        GOOS=linux GOARCH=arm64 go build -o cut.linux-arm64 .
        GOOS=linux GOARCH=ppc64 go build -o cut.linux-ppc64 .
        GOOS=linux GOARCH=ppc64le go build -o cut.linux-ppc64le .
        GOOS=linux GOARCH=mips go build -o cut.linux-mips .
        GOOS=linux GOARCH=mipsle go build -o cut.linux-mipsle .
        GOOS=linux GOARCH=mips64 go build -o cut.linux-mips64 .
        GOOS=linux GOARCH=mips64le go build -o cut.linux-mips64le .
        GOOS=linux GOARCH=s390x go build -o cut.linux-s390x .
        GOOS=netbsd GOARCH=386 go build -o cut.netbsd-386 .
        GOOS=netbsd GOARCH=amd64 go build -o cut.netbsd-amd64 .
        GOOS=netbsd GOARCH=arm go build -o cut.netbsd-arm .
        GOOS=openbsd GOARCH=386 go build -o cut.openbsd-386 .
        GOOS=openbsd GOARCH=amd64 go build -o cut.openbsd-amd64 .
        GOOS=openbsd GOARCH=arm go build -o cut.openbsd-arm .
        GOOS=openbsd GOARCH=arm64 go build -o cut.openbsd-arm64 .
        GOOS=plan9 GOARCH=386 go build -o cut.plan9-386 .
        GOOS=plan9 GOARCH=amd64 go build -o cut.plan9-amd64 .
        GOOS=plan9 GOARCH=arm go build -o cut.plan9-arm .
        GOOS=solaris GOARCH=amd64 go build -o cut.solaris-amd64 .
        GOOS=windows GOARCH=386 go build -o cut.windows-386 .
        GOOS=windows GOARCH=386 go build -o cut.plan9-amd64 .
